image: ponders/godot-cpp-ci:latest

# Cache compiled bindings between runs
cache:
  key: compiled-bindings
  paths:
    - $PROJECT_FOLDER/godot-cpp/bin/

stages:
  - export

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_FOLDER: gdextension_cpp_example
  TARGET_NAME: libgdexample

# Linux shared libraries are humongous (>70MB) for some reason.. don't forget to strip them!
linux:
  stage: export
  variables:
    TARGET_PATH: demo/bin/
  parallel:
    matrix:
      - TARGET:
        - template_debug
        - template_release
  environment: $TARGET
  script:
    - mkdir -v -p $PROJECT_FOLDER/$TARGET_PATH
    - cd $PROJECT_FOLDER
    - scons platform=linux target=$TARGET target_path=$TARGET_PATH target_name=$TARGET_NAME -j6
  artifacts:
    name: linux
    paths:
      - $PROJECT_FOLDER/$TARGET_PATH

windows:
  stage: export
  variables:
    TARGET_PATH: demo/bin/
  parallel:
    matrix:
      - TARGET:
        - template_debug
        - template_release
  environment: $TARGET
  script:
    - mkdir -v -p $PROJECT_FOLDER/$TARGET_PATH
    - cd $PROJECT_FOLDER
    - scons platform=windows target=$TARGET target_path=$TARGET_PATH target_name=$TARGET_NAME -j6
  artifacts:
    name: windows
    paths:
      - $PROJECT_FOLDER/$TARGET_PATH