name: 🤖 Android Builds
on: push

# Global Settings
env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: test-project

jobs:
  android-compilation:
    name: Android Compilation
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        with:
            lfs: true
            submodules: recursive

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
        run: |
          mkdir -v -p gdnative_cpp_example/demo/bin/android/arm64_v8a
          cd gdnative_cpp_example
          cd godot-cpp
          scons platform=android bits=64 android_arch=arm64v8 target=debug generate_bindings=yes -j4
          cd ..
          $ANDROID_NDK_ROOT/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_PLATFORM=android-21 NDK_LIBS_OUT=./demo/bin/android
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: gdnative_cpp_example/demo/bin/android/arm64_v8a
