name: 🍎 macOS Builds
on: push

# Global Settings
env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: test-project

jobs:
  macos-compilation:
    name: MacOS Compilation
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Linux Build
        run: |
          mkdir -v -p gdnative_cpp_example/demo/bin/osx
          cd gdnative_cpp_example
          cd godot-cpp
          scons platform=osx bits=64 target=debug generate_bindings=yes -j4
          cd ..
          scons platform=osx

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx
          path: gdnative_cpp_example/demo/bin/osx
